/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.qi.gestaohc.views;

import br.edu.qi.gestaohc.controllers.ClAluno;
import br.edu.qi.gestaohc.controllers.ClAtividadeComplementar;
import br.edu.qi.gestaohc.controllers.ClCurso;
import br.edu.qi.gestaohc.controllers.ClHorasComplementares;
import br.edu.qi.gestaohc.model.Aluno;
import br.edu.qi.gestaohc.model.AtividadeComplementar;
import br.edu.qi.gestaohc.model.Curso;
import br.edu.qi.gestaohc.model.HorasComplementares;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anderson
 */
public class VwHorasComplementares extends javax.swing.JFrame {
    
    private HorasComplementares hc;
    private ClHorasComplementares clhc;
    private ClAluno cla = new ClAluno();
    private ClCurso clc = new ClCurso();
    private ClAtividadeComplementar clac = new ClAtividadeComplementar();
    private static Map<Integer, Aluno> mapAlunos = new HashMap<Integer, Aluno>();
    private static Map<Integer, Curso> mapCursos = new HashMap<Integer, Curso>();
    private static Map<Integer, AtividadeComplementar> mapAtividades = new HashMap<Integer, AtividadeComplementar>();
    
    /**
     * Creates new form VwHorasComplementares
     */
    public VwHorasComplementares() throws SQLException {     
        initComponents();
        List<Curso> cursos = clc.listarTodosCursos();
        List<Aluno> alunos = cla.listarTodosAluno();
        List<AtividadeComplementar> ativComps = clac.listarTodasAtividadeComplementar();
        this.cbxCurso.removeAll();
        this.cbxAluno.removeAll();
        this.cbxAtividadeComplementar.removeAll();
        
        // Indexar.
        int i = 0;
        for (Aluno aluno : alunos) {
            this.cbxAluno.addItem(aluno.getRa() + " - " + aluno.getNome());
            mapAlunos.put(i, aluno);
            i++;
        }
        
        i = 0;
        for (AtividadeComplementar ativComp : ativComps) {
            this.cbxAtividadeComplementar.addItem(ativComp.getId() + " - " + ativComp.getNome());
            mapAtividades.put(i, ativComp);
            i++;
        }
        
        i = 0;
        for (Curso curso : cursos) {
            this.cbxCurso.addItem(curso.getId() + " - " + curso.getNome());
            mapCursos.put(i, curso);
            i++;
        }
        this.listarHorasComplementares();
    }
    
    public void criarVwHorasComplementares() {

    }

    public HorasComplementares receberHorasComplementares() throws SQLException, ParseException {
        
        String codHC = txtRHC.getText();
        
        Aluno aluno = mapAlunos.get(cbxAluno.getSelectedIndex());
        Curso curso = mapCursos.get(cbxCurso.getSelectedIndex());
        AtividadeComplementar ativComp = mapAtividades.get(cbxAtividadeComplementar.getSelectedIndex());
        
        String dataHC = this.data.getText();
        String descricao = this.descricao.getText();
        String totalHC = this.txtLHAC.getText();
        
        HorasComplementares horasComplementares = new HorasComplementares();        
        horasComplementares.setAluno(aluno);
        horasComplementares.setCurso(curso);
        horasComplementares.setAc(ativComp);
        
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        horasComplementares.setData(formato.parse(dataHC));
        horasComplementares.setDescricao(descricao);
        horasComplementares.setHora_total(Integer.parseInt(totalHC));
                
        return horasComplementares;
    }  

    public void exibirMensagem(String msg) {
        JOptionPane.showMessageDialog(null, msg, "Mensagem!", JOptionPane.DEFAULT_OPTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRHC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbxCurso = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtLHAC = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cbxAluno = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbxAtividadeComplementar = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        data = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descricao = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de Horas Complementares");

        jLabel2.setText("Código RHC:");

        jLabel3.setText("Aluno:");

        txtRHC.setEnabled(false);
        txtRHC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRHCActionPerformed(evt);
            }
        });

        jLabel4.setText("Curso:");

        jLabel5.setText("Total de horas da atividade:");

        txtLHAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLHACActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton4.setText("Filtrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("Inserir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Atualizar");

        jButton3.setText("Excluir");

        cbxAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAlunoActionPerformed(evt);
            }
        });

        jLabel6.setText("Atividade:");

        cbxAtividadeComplementar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAtividadeComplementarActionPerformed(evt);
            }
        });

        jLabel7.setText("Data da atividade:");

        try {
            data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        data.setText("00/00/0000    ");
        data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataActionPerformed(evt);
            }
        });

        jLabel8.setText("Descrição da atividade complementar:");

        descricao.setColumns(20);
        descricao.setRows(5);
        jScrollPane2.setViewportView(descricao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxAtividadeComplementar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRHC, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(5, 5, 5)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLHAC, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbxAluno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRHC))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxAtividadeComplementar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtLHAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRHCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRHCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRHCActionPerformed

    private void txtLHACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLHACActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLHACActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            clhc = new ClHorasComplementares();
            clhc.gravarHorasComplementares(this.receberHorasComplementares());
            //             Atualizar tabela após inserir.
            this.listarHorasComplementares();
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbxAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxAlunoActionPerformed

    private void cbxAtividadeComplementarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAtividadeComplementarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxAtividadeComplementarActionPerformed

    private void dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VwHorasComplementares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VwHorasComplementares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VwHorasComplementares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VwHorasComplementares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VwHorasComplementares().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(VwHorasComplementares.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxAluno;
    private javax.swing.JComboBox<String> cbxAtividadeComplementar;
    private javax.swing.JComboBox<String> cbxCurso;
    private javax.swing.JFormattedTextField data;
    private javax.swing.JTextArea descricao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtLHAC;
    private javax.swing.JTextField txtRHC;
    // End of variables declaration//GEN-END:variables

    private void listarHorasComplementares() throws SQLException {
        clhc = new ClHorasComplementares();
        List<HorasComplementares> listHorasComplementares = clhc.listarTodasHorasComplementares();        
        
        clac = new ClAtividadeComplementar();
        List<AtividadeComplementar> listAtividadesComplementares = clac.listarTodasAtividadesComplementares();
        
        cla = new ClAluno();
        List<Aluno> listAlunos = cla.listarTodosAlunos();

        clc = new ClCurso();
        List<Curso> listCurso = clc.listarTodosCursos();
        
        DefaultTableModel modelinho = new DefaultTableModel();
        modelinho.addColumn("Aluno");
        modelinho.addColumn("Curso");
        modelinho.addColumn("Atividade");
        modelinho.addColumn("Data");
        modelinho.addColumn("Descrição RHC");
        modelinho.addColumn("Total de Horas");

        for(HorasComplementares hc : listHorasComplementares){             
            modelinho.addRow(new Object[]{
                hc.getAluno().getNome(),
                hc.getCurso().getNome(),
                hc.getAc().getNome(),
                hc.getData().toString(),
                hc.getDescricao(),
                hc.getHora_total().toString()
            });            
            jTable1.setModel(modelinho);               
        }    
    }
}
